<?php

//DEFINE MORSECODE
$morse = array(
    "a" => array("A", ".-"),
    "b" => array("B", "-..."),
    "c" => array("C", "-.-."),
    "d" => array("D", "-.."),
    "e" => array("E", "."),
    "f" => array("F", "..-."),
    "g" => array("G", "--."),
    "h" => array("H", "...."),
    "ch" => array("CH", "----"),
    "i" => array("I", ".."),
    "j" => array("J", ".---"),
    "k" => array("K", "-.-"),
    "l" => array("L", ".-.."),
    "m" => array("M", "--"),
    "n" => array("N", "-."),
    "o" => array("O", "---"),
    "p" => array("P", ".--."),
    "q" => array("Q", "--.-"),
    "r" => array("R", ".-."),
    "s" => array("S", "..."),
    "t" => array("T", "-"),
    "u" => array("U", "..-"),
    "v" => array("V", "...-"),
    "w" => array("W", ".--"),
    "x" => array("X", "-..-"),
    "y" => array("Y", "-.--"),
    "z" => array("Z", "--.."),
    " " => array(" ", "/"),
    "0" => array("0", ".----"),
    "1" => array("1", "..---"),
    "2" => array("2", "...--"),
    "3" => array("3", "....-"),
    "4" => array("4", "....."),
    "5" => array("5", "-...."),
    "6" => array("6", "--..."),
    "7" => array("7", "---.."),
    "8" => array("8", "----."),
    "9" => array("9", "-----"),
    "?" => array("?", "..--.."),
    "," => array(",", "--..--"),
    "!" => array("!", "--...-"),
    "." => array(".", ".-.-.-"),
    ";" => array(";", "-.-.-."),
    "/" => array("/", "-..-."),
    "=" => array("=", "-...-"),
    "-" => array("-", "-....-"),
    "\t" => array("\t", ".----."),
    "(" => array("(", "-.--."),
    ")" => array(")", "-.--.-"),
    "\"" => array("?", ".-..-."),
    ":" => array(":", "---..."),
    "_" => array("_", "..--.-"),
    "@" => array("@", ".--.-."),
);

$morse_buffer = array();
foreach ($morse as $temp) {
        array_push($morse_buffer,$temp[1]);
}
?>
